import type{Company}from'./v2-types';

export type EpiPdfRequest={
 id:string;createdAt:string;status:string;type:string;reason?:string;user:string;company:Company;sector:string;
 items:Array<{name:string;quantity:number;deliveredQuantity?:number}>;attendant?:string;deliveryDate?:string;deliveryNotes?:string;
 techSignature?:string;employeeSignature?:string;
};

const PAGE_WIDTH=1240,PAGE_HEIGHT=1754,MARGIN=90,TEAL='#00858d',INK='#172033',MUTED='#78818d',BORDER='#c8cdd3';
const employee={cpf:'***.482.***-**',email:'carlos.lima@operix.local',registration:'COL-0142',admission:'12/03/2022',job:'Operador de maquina'};

function loadImage(source?:string){return new Promise<HTMLImageElement|null>(resolve=>{if(!source)return resolve(null);const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=source})}
function fitImage(ctx:CanvasRenderingContext2D,image:HTMLImageElement,x:number,y:number,width:number,height:number){const ratio=Math.min(width/image.naturalWidth,height/image.naturalHeight),drawWidth=image.naturalWidth*ratio,drawHeight=image.naturalHeight*ratio;ctx.drawImage(image,x+(width-drawWidth)/2,y+(height-drawHeight)/2,drawWidth,drawHeight)}
function roundedRect(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number,radius=6){ctx.beginPath();ctx.roundRect(x,y,width,height,radius)}
function wrapText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,maxLines=4){const words=String(text||'-').split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word;if(lines.length===maxLines-1)break}else line=next}if(line&&lines.length<maxLines)lines.push(line);return lines}
function section(ctx:CanvasRenderingContext2D,title:string,y:number){ctx.fillStyle='#9aa1a9';ctx.font='700 15px Arial';ctx.fillText(title.toUpperCase(),MARGIN+20,y);return y+22}
function field(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number,label:string,value:string,accent=false){ctx.fillStyle='#fff';ctx.strokeStyle=BORDER;ctx.lineWidth=1.5;roundedRect(ctx,x,y,width,height);ctx.fill();ctx.stroke();ctx.fillStyle=MUTED;ctx.font='700 13px Arial';ctx.fillText(label.toUpperCase(),x+15,y+20);ctx.fillStyle=accent?'#9a6900':INK;ctx.font=`${accent?'700':'400'} 17px Arial`;wrapText(ctx,value,width-30,Math.max(1,Math.floor((height-30)/20))).forEach((line,index)=>ctx.fillText(line,x+15,y+44+index*20))}
function drawSignature(ctx:CanvasRenderingContext2D,image:HTMLImageElement|null,x:number,y:number,width:number,label:string){if(image)fitImage(ctx,image,x+40,y,width-80,85);ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y+102);ctx.lineTo(x+width,y+102);ctx.stroke();ctx.fillStyle=INK;ctx.font='700 13px Arial';ctx.textAlign='center';ctx.fillText(label,x+width/2,y+124);ctx.textAlign='left'}
function drawEpiBox(ctx:CanvasRenderingContext2D,request:EpiPdfRequest,y:number,width:number){const rows=Math.max(1,Math.ceil(request.items.length/2)),height=42+rows*29;ctx.fillStyle='#fff';ctx.strokeStyle=BORDER;ctx.lineWidth=1.5;roundedRect(ctx,MARGIN,y,width,height);ctx.fill();ctx.stroke();ctx.font='700 16px Arial';ctx.fillStyle=INK;request.items.forEach((item,index)=>{const column=index%2,row=Math.floor(index/2),columnWidth=(width-32)/2,x=MARGIN+16+column*columnWidth,text=`${item.name} - Qtd.: ${item.deliveredQuantity??item.quantity}`;ctx.fillText(text.length>56?text.slice(0,53)+'...':text,x,y+31+row*29)});return y+height}
function toPtBrDate(value?:string){if(!value)return '-';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value.split(' ')[0]:parsed.toLocaleDateString('pt-BR')}
function fallbackLogo(company:Company){const colors:Record<Company,string>={Grafmarques:'#0b8f7d',INFINNI:'#17233c','M.Print':'#4361c2'},initials:Record<Company,string>={Grafmarques:'GM',INFINNI:'IN','M.Print':'MP'};return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="100"><rect width="160" height="100" rx="12" fill="${colors[company]}"/><text x="80" y="61" text-anchor="middle" font-family="Arial" font-size="36" font-weight="700" fill="white">${initials[company]}</text></svg>`)}`}
function download(canvas:HTMLCanvasElement,name:string){const anchor=document.createElement('a');anchor.href=canvas.toDataURL('image/jpeg',.96);anchor.download=name.replace('.pdf','.jpg');anchor.click()}

export async function downloadEpiFormPdf(request:EpiPdfRequest){
 const canvas=document.createElement('canvas');canvas.width=PAGE_WIDTH;canvas.height=PAGE_HEIGHT;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,PAGE_WIDTH,PAGE_HEIGHT);ctx.textBaseline='alphabetic';
 const storedLogo=localStorage.getItem(`operix.company.logo.${request.company}`)||fallbackLogo(request.company);
 const[logo,technicianSignature,employeeSignature]=await Promise.all([loadImage(storedLogo),loadImage(request.techSignature),loadImage(request.employeeSignature)]);
 if(logo)fitImage(ctx,logo,MARGIN,42,115,72);
 ctx.fillStyle=INK;ctx.font='700 23px Arial';ctx.fillText(request.company,MARGIN+135,77);ctx.fillStyle=MUTED;ctx.font='14px Arial';ctx.fillText('Seguranca do Trabalho',MARGIN+135,101);ctx.textAlign='right';ctx.fillText(`Ficha: ${request.id}`,PAGE_WIDTH-MARGIN,71);ctx.fillText(new Date().toLocaleString('pt-BR'),PAGE_WIDTH-MARGIN,96);ctx.textAlign='center';ctx.fillStyle=TEAL;ctx.font='700 23px Arial';ctx.fillText('FICHA DE ENTREGA DE EQUIPAMENTO DE PROTECAO INDIVIDUAL (EPI)',PAGE_WIDTH/2,157);ctx.fillStyle=MUTED;ctx.font='14px Arial';ctx.fillText('Conforme NR-6 e legislacao de Seguranca e Saude no Trabalho',PAGE_WIDTH/2,184);ctx.strokeStyle=TEAL;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(MARGIN,213);ctx.lineTo(PAGE_WIDTH-MARGIN,213);ctx.stroke();ctx.textAlign='left';
 const gap=14,totalWidth=PAGE_WIDTH-MARGIN*2,columnWidth=(totalWidth-gap)/2,fieldHeight=64;let y=252;
 y=section(ctx,'Dados do colaborador',y);field(ctx,MARGIN,y,columnWidth,fieldHeight,'Nome completo',request.user);field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'CPF',employee.cpf);y+=fieldHeight+gap;field(ctx,MARGIN,y,columnWidth,fieldHeight,'E-mail',employee.email);field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'Matricula',employee.registration);y+=fieldHeight+gap;field(ctx,MARGIN,y,columnWidth,fieldHeight,'Data de admissao',employee.admission);y+=fieldHeight+42;
 y=section(ctx,'Dados profissionais',y);field(ctx,MARGIN,y,columnWidth,fieldHeight,'Funcao',employee.job);field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'Setor',request.sector);y+=fieldHeight+gap;field(ctx,MARGIN,y,columnWidth,fieldHeight,'Empresa',request.company);field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'Tipo de solicitacao',request.type);y+=fieldHeight+42;
 y=section(ctx,'EPIs solicitados / entregues',y);y=drawEpiBox(ctx,request,y,totalWidth);if(request.reason){y+=gap;field(ctx,MARGIN,y,totalWidth,72,'Motivo / justificativa',request.reason);y+=72}y+=42;
 y=section(ctx,'Dados da entrega',y);field(ctx,MARGIN,y,columnWidth,fieldHeight,'Responsavel pela entrega',request.attendant||'-');field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'Data da entrega',toPtBrDate(request.deliveryDate));y+=fieldHeight+gap;field(ctx,MARGIN,y,columnWidth,fieldHeight,'Status',request.status,request.status!=='Entregue');field(ctx,MARGIN+columnWidth+gap,y,columnWidth,fieldHeight,'Data da solicitacao',toPtBrDate(request.createdAt));y+=fieldHeight+gap;if(request.deliveryNotes){field(ctx,MARGIN,y,totalWidth,70,'Observacoes do tecnico',request.deliveryNotes);y+=84}
 const signatureY=Math.max(y+22,1330);drawSignature(ctx,technicianSignature,MARGIN,signatureY,columnWidth,'Assinatura do Responsavel pela Entrega');drawSignature(ctx,employeeSignature,MARGIN+columnWidth+gap,signatureY,columnWidth,'Assinatura do Colaborador');
 const termY=Math.max(signatureY+165,1510);ctx.fillStyle=INK;ctx.font='700 13px Arial';ctx.fillText('Termo de Responsabilidade:',MARGIN+18,termY);ctx.font='12px Arial';const term='Declaro que recebi os Equipamentos de Protecao Individual (EPIs) listados nesta ficha em perfeitas condicoes de uso, fui orientado quanto a utilizacao, guarda e conservacao, e estou ciente das obrigacoes previstas na NR-6 e na legislacao vigente.';wrapText(ctx,term,totalWidth-36,5).forEach((line,index)=>ctx.fillText(line,MARGIN+18,termY+21+index*18));ctx.strokeStyle='#d4d7dc';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(MARGIN,1681);ctx.lineTo(PAGE_WIDTH-MARGIN,1681);ctx.stroke();ctx.fillStyle=MUTED;ctx.font='11px Arial';ctx.textAlign='center';ctx.fillText(`Documento gerado em ${new Date().toLocaleString('pt-BR')} | ${request.company} | ${request.id}`,PAGE_WIDTH/2,1708);ctx.textAlign='right';ctx.fillText('1/1',PAGE_WIDTH-MARGIN,1708);
 const jpeg=atob(canvas.toDataURL('image/jpeg',.96).split(',')[1]),content='q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n',objects:string[]=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]='<< /Type /Pages /Count 1 /Kids [3 0 R] >>';objects[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>';objects[4]=`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n${jpeg}\nendstream`;objects[5]=`<< /Length ${content.length} >>\nstream\n${content}endstream`;let pdf='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n',offsets=[0];for(let index=1;index<objects.length;index++){offsets[index]=pdf.length;pdf+=`${index} 0 obj\n${objects[index]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const bytes=Uint8Array.from(pdf,character=>character.charCodeAt(0)&255),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`ficha-${request.id}.pdf`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
