import React,{useState}from'react';
import{createPortal}from'react-dom';
import{CalendarDays,Check,ClipboardCheck,Eye,FileCheck2,Pencil,Plus,Printer,Save,Trash2,X,XCircle}from'lucide-react';
import type{ChecklistAnswer,ChecklistResult,Order,Ticket}from'./v2-types';
import{ExportButtons,type ExportColumn,type ExportRow}from'./data-export';
import{printWorkOrder}from'./work-order-print';

type Schedule={id:number;target:string;date:string;service:string;priority:string;checklist:string;orderId?:string};
type Checklist={id:number;name:string;items:string[]};
const initialSchedules:Schedule[]=[];
const initialChecks:Checklist[]=[];
const notify=(message:string)=>{let banner=document.getElementById('v2-toast');if(!banner){banner=document.createElement('div');banner.id='v2-toast';banner.className='toast-inline';document.body.appendChild(banner)}banner.textContent=message;banner.style.display='flex';setTimeout(()=>banner!.style.display='none',2500)};
function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:React.ReactNode;wide?:boolean}){return createPortal(<div className="overlay v2-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className={`modal v2-modal ${wide?'management-wide-modal':''}`} role="dialog" aria-modal="true" aria-label={title}><div><h2>{title}</h2><button type="button" aria-label="Fechar" onClick={close}><X/></button></div>{children}</div></div>,document.body)}
function Actions({edit,remove}:{edit:()=>void;remove:()=>void}){return <div className="maintenance-crud"><button type="button" aria-label="Editar" onClick={event=>{event.stopPropagation();edit()}}><Pencil/></button><button type="button" className="danger" aria-label="Excluir" onClick={event=>{event.stopPropagation();remove()}}><Trash2/></button></div>}

export default function MaintenanceV4({orders,tickets,sectors,area='Manutenção',approve,deny,openOrder}:{orders:Order[];tickets:Ticket[];sectors:string[];area?:'Manutenção'|'T.I.';approve:(ticket:Ticket)=>void;deny:(ticket:Ticket,reason:string)=>void;openOrder:(id:string)=>void}){
 const[tab,setTab]=useState<'orders'|'schedule'|'checklists'>('orders'),[scheduleEditor,setScheduleEditor]=useState<Schedule|null|undefined>(undefined),[checkEditor,setCheckEditor]=useState<Checklist|null|undefined>(undefined),[schedules,setSchedules]=useState<Schedule[]>(initialSchedules),[checks,setChecks]=useState<Checklist[]>(initialChecks),[from,setFrom]=useState(''),[to,setTo]=useState(''),[ticketDetail,setTicketDetail]=useState<Ticket|null>(null),[denyTicket,setDenyTicket]=useState<Ticket|null>(null),[denyReason,setDenyReason]=useState(''),[detailId,setDetailId]=useState<string|null>(null),[checkRun,setCheckRun]=useState<Checklist|null>(null),[checkResults,setCheckResults]=useState<Record<number,Record<string,ChecklistAnswer>>>({}),[checkError,setCheckError]=useState('');
 const pending=tickets.filter(ticket=>ticket.status==='Novo'),detail=orders.find(order=>order.id===detailId),runAnswers=checkRun?checkResults[checkRun.id]||{}:{};
 const exportData:{title:string;columns:ExportColumn[];rows:ExportRow[]}=tab==='orders'?{title:`Ordens de serviço - ${area}`,columns:[{key:'codigo',label:'Código'},{key:'solicitante',label:'Solicitante'},{key:'chamado',label:'Data do chamado'},{key:'aprovacao',label:'Data da aprovação'},{key:'situacao',label:'Situação'}],rows:orders.map(item=>({codigo:item.id,solicitante:item.requester,chamado:item.openedAt,aprovacao:item.approvedAt||'-',situacao:item.status}))}:tab==='schedule'?{title:`Cronograma preventivo - ${area}`,columns:[{key:'equipamento',label:'Setor/equipamento'},{key:'data',label:'Data'},{key:'servico',label:'Serviço'},{key:'ordem',label:'Ordem vinculada'}],rows:schedules.map(item=>({equipamento:item.target,data:item.date,servico:item.service,ordem:item.orderId||'-'}))}:{title:`Checklists - ${area}`,columns:[{key:'nome',label:'Nome'},{key:'itens',label:'Itens'}],rows:checks.map(item=>({nome:item.name,itens:item.items.join('; ')}))};
 const setCheckAnswer=(item:string,result:ChecklistResult)=>{if(!checkRun)return;setCheckResults(current=>({...current,[checkRun.id]:{...(current[checkRun.id]||{}),[item]:{result,justification:current[checkRun.id]?.[item]?.justification||''}}}))};
 const saveChecklistRun=()=>{if(!checkRun)return;const answers=checkResults[checkRun.id]||{},valid=checkRun.items.every(item=>answers[item]&&(answers[item].result!=='NAO'||answers[item].justification?.trim()));if(!valid){setCheckError('Responda todos os itens e justifique obrigatoriamente cada resposta “Não”.');return}setCheckError('');setCheckRun(null);notify('Checklist preenchido e registrado com sucesso.')};
 return <section className="content page-enter management-page"><div className="page-title"><div><span>{area==='T.I.'?'TECNOLOGIA DA INFORMAÇÃO':'MANUTENÇÃO'}</span><h1>{area==='T.I.'?'Gestão de TI':'Gestão de Manutenção'}</h1><p>Aprovação de chamados, ordens, cronogramas e checklists exclusivos do setor.</p></div><div className="page-title-actions"><ExportButtons {...exportData}/>{tab==='schedule'&&<button type="button" className="primary" onClick={()=>setScheduleEditor(null)}><Plus/>Novo cronograma</button>}{tab==='checklists'&&<button type="button" className="primary" onClick={()=>setCheckEditor(null)}><Plus/>Novo checklist</button>}</div></div><div className="management-tabs"><button type="button" className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Chamados e ordens</button><button type="button" className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}>Cronograma preventivo</button><button type="button" className={tab==='checklists'?'active':''} onClick={()=>setTab('checklists')}>Checklists</button></div>
 {tab==='orders'&&<><section className="panel management-ticket-queue"><div className="content-head"><div><h2>Chamados aguardando decisão</h2><p>{pending.length} solicitação(ões) direcionada(s) para {area}</p></div></div>{pending.map(ticket=><button type="button" onClick={()=>setTicketDetail(ticket)} key={ticket.id}><span className="ticket-state novo">Novo</span><div><b>{ticket.id} · {ticket.request}</b><small>{ticket.requester} · {ticket.createdAt} · {ticket.sector}</small></div><Eye/></button>)}{!pending.length&&<div className="empty-list compact">Nenhum chamado aguardando aprovação.</div>}</section><div className="date-filters"><label>Abertura a partir de<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Fechamento até<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div><div className="maintenance-list management-order-list">{orders.map(order=><button type="button" className="panel" onClick={()=>setDetailId(order.id)} key={order.id}><div><b>{order.id}</b><span>{order.status}</span><h3>{order.request}</h3><small>Solicitante: {order.requester} · Chamado: {order.openedAt}</small><small>Aprovação: {order.approvedAt||'Não informada'} · Encerramento: {order.closedAt||'-'}</small></div><span className="order-open-hint"><Eye/>Abrir ordem</span></button>)}{!orders.length&&<div className="empty-list">Nenhuma ordem deste setor.</div>}</div></>}
 {tab==='schedule'&&<div className="maintenance-list editable-maintenance-list">{schedules.map(item=>{const linked=orders.find(order=>order.id===item.orderId);return <article className="panel clickable-record" onClick={()=>linked?setDetailId(linked.id):setScheduleEditor(item)} key={item.id}><CalendarDays/><div><h3>{item.target}</h3><small>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')} · {item.service} · Prioridade {item.priority}</small><p>Checklist: {item.checklist||'Sem checklist'}{linked?` · ${linked.id}`:''}</p></div><Actions edit={()=>setScheduleEditor(item)} remove={()=>setSchedules(current=>current.filter(schedule=>schedule.id!==item.id))}/></article>})}</div>}
 {tab==='checklists'&&<div className="maintenance-list editable-maintenance-list">{checks.map(item=><article className="panel clickable-record" onClick={()=>{setCheckRun(item);setCheckError('')}} key={item.id}><ClipboardCheck/><div><h3>{item.name}</h3><small>{item.items.length} itens · Clique para preencher</small><p>{item.items.join(' · ')}</p></div><Actions edit={()=>setCheckEditor(item)} remove={()=>setChecks(current=>current.filter(check=>check.id!==item.id))}/></article>)}</div>}
 {ticketDetail&&<Modal title={`Analisar chamado ${ticketDetail.id}`} close={()=>setTicketDetail(null)} wide><div className="management-ticket-detail"><dl className="order-detail-grid"><div><dt>Solicitante</dt><dd>{ticketDetail.requester}</dd></div><div><dt>Data e hora</dt><dd>{ticketDetail.createdAt}</dd></div><div><dt>Setor</dt><dd>{ticketDetail.sector}</dd></div><div><dt>Ramal</dt><dd>{ticketDetail.extension}</dd></div><div className="wide"><dt>Solicitação</dt><dd>{ticketDetail.request}</dd></div></dl><div className="decision-actions"><button className="deny-btn" onClick={()=>{setDenyTicket(ticketDetail);setTicketDetail(null)}}><XCircle/>Negar</button><button className="primary" onClick={()=>{approve(ticketDetail);setTicketDetail(null)}}><FileCheck2/>Aprovar e criar OS</button></div></div></Modal>}
 {denyTicket&&<Modal title={`Negar chamado ${denyTicket.id}`} close={()=>setDenyTicket(null)}><label className="deny-reason-field">Justificativa obrigatória<textarea value={denyReason} minLength={5} onChange={event=>setDenyReason(event.target.value)} placeholder="Informe claramente o motivo da negativa."/></label><div className="form-actions"><button onClick={()=>setDenyTicket(null)}>Cancelar</button><button className="deny-btn" disabled={denyReason.trim().length<5} onClick={()=>{deny(denyTicket,denyReason.trim());setDenyTicket(null);setDenyReason('')}}><XCircle/>Confirmar negativa</button></div></Modal>}
 {detail&&<Modal title={`Ordem de serviço ${detail.id}`} close={()=>setDetailId(null)} wide><dl className="order-detail-grid"><div><dt>Solicitante</dt><dd>{detail.requester}</dd></div><div><dt>Chamado</dt><dd>{detail.openedAt}</dd></div><div><dt>Aprovação como OS</dt><dd>{detail.approvedAt||'Não informada'}</dd></div><div><dt>Situação</dt><dd>{detail.status}</dd></div><div><dt>Técnico</dt><dd>{detail.technician||'Não definido'}</dd></div><div><dt>Encerramento</dt><dd>{detail.closedAt||'-'}</dd></div><div className="wide"><dt>Solicitação</dt><dd>{detail.request}</dd></div><div className="wide"><dt>Serviço realizado</dt><dd>{detail.workDone||'Aguardando execução'}</dd></div></dl><div className="form-actions"><button onClick={()=>printWorkOrder(detail)}><Printer/>Imprimir OS</button><button className="primary" onClick={()=>openOrder(detail.id)}><Eye/>Abrir para execução</button></div></Modal>}
 {scheduleEditor!==undefined&&<Modal title={scheduleEditor?'Editar cronograma preventivo':'Novo cronograma preventivo'} close={()=>setScheduleEditor(undefined)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),record:Schedule={id:scheduleEditor?.id||Date.now(),target:String(data.get('target')),date:String(data.get('date')),service:String(data.get('service')),priority:String(data.get('priority')),checklist:String(data.get('checklist')),orderId:String(data.get('orderId')||'')||undefined};setSchedules(current=>scheduleEditor?current.map(item=>item.id===record.id?record:item):[...current,record]);setScheduleEditor(undefined)}}><label>Setor/equipamento<select name="target" defaultValue={scheduleEditor?.target||sectors[0]}>{sectors.map(sector=><option key={sector}>{sector}</option>)}<option>CNC 03</option><option>Plotter 01</option><option>Compressor</option></select></label><label>Data<input name="date" type="date" defaultValue={scheduleEditor?.date} required/></label><label>Tipo de serviço<select name="service" defaultValue={scheduleEditor?.service||'Preventiva'}><option>Limpeza</option><option>Preventiva</option><option>Troca de equipamento</option><option>Substituição</option></select></label><label>Prioridade<select name="priority" defaultValue={scheduleEditor?.priority||'Normal'}><option>Normal</option><option>Alta</option><option>Crítica</option></select></label><label>Checklist<select name="checklist" defaultValue={scheduleEditor?.checklist||''}><option value="">Sem checklist</option>{checks.map(check=><option key={check.id}>{check.name}</option>)}</select></label><label>Ordem de serviço vinculada<select name="orderId" defaultValue={scheduleEditor?.orderId||''}><option value="">Sem OS vinculada</option>{orders.map(order=><option key={order.id} value={order.id}>{order.id} · {order.request}</option>)}</select></label><button className="primary"><Save/>Salvar cronograma</button></form></Modal>}
 {checkEditor!==undefined&&<Modal title={checkEditor?'Editar checklist':'Criar checklist'} close={()=>setCheckEditor(undefined)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),record:Checklist={id:checkEditor?.id||Date.now(),name:String(data.get('name')),items:String(data.get('items')).split('\n').map(item=>item.trim()).filter(Boolean)};setChecks(current=>checkEditor?current.map(item=>item.id===record.id?record:item):[...current,record]);setCheckEditor(undefined)}}><label>Nome<input name="name" defaultValue={checkEditor?.name} required/></label><label>Itens do checklist<textarea name="items" defaultValue={checkEditor?.items.join('\n')} placeholder="Um item por linha" required/></label><button className="primary"><Save/>Salvar checklist</button></form></Modal>}
 {checkRun&&<Modal title={`Preencher checklist - ${checkRun.name}`} close={()=>setCheckRun(null)} wide><div className="checklist-execution">{checkRun.items.map(item=>{const answer=runAnswers[item];return <article key={item}><b>{item}</b><div className="checklist-answer-options">{([['SIM','Sim'],['NAO','Não'],['NAO_SE_APLICA','Não se aplica']]as[ChecklistResult,string][]).map(([value,label])=><label className={answer?.result===value?'selected':''} key={value}><input type="radio" name={`${checkRun.id}-${item}`} checked={answer?.result===value} onChange={()=>setCheckAnswer(item,value)}/><span>{label}</span></label>)}</div>{answer?.result==='NAO'&&<label>Justificativa obrigatória<textarea value={answer.justification||''} onChange={event=>setCheckResults(current=>({...current,[checkRun.id]:{...(current[checkRun.id]||{}),[item]:{...answer,justification:event.target.value}}}))} placeholder="Descreva a não conformidade e a ação necessária."/></label>}</article>})}{checkError&&<div className="form-alert">{checkError}</div>}<button className="primary" onClick={saveChecklistRun}><Check/>Salvar checklist preenchido</button></div></Modal>}
 </section>
}
