import React,{useState}from'react';
import{Star}from'lucide-react';
import type{Order,Role}from'./v2-types';
import OrdersV3 from'./OrdersV3';
import{ExportButtons}from'./data-export';

export default function OrdersHub({orders,role,update,remove}:{orders:Order[];role:Role;update:(order:Order)=>void;remove:(id:string)=>void}){
 const[tab,setTab]=useState<'orders'|'reviews'>('orders'),ratings=['Excelente','Bom','Regular','Ruim','Péssimo','Não realizado'];
 return <><div className="module-subnav"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Ordens de serviço</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}><Star/>Avaliações</button></div>{tab==='orders'?<OrdersV3 orders={orders} role={role} update={update} remove={remove}/>:<section className="content page-enter orders-review-page"><div className="page-title"><div><span>ORDENS DE SERVIÇO</span><h1>Avaliações dos atendimentos</h1><p>Notas e justificativas obrigatórias registradas pelos solicitantes.</p></div><ExportButtons title="Avaliações das ordens de serviço" columns={[{key:'ordem',label:'Ordem'},{key:'solicitante',label:'Solicitante'},{key:'chamado',label:'Data do chamado'},{key:'aprovacao',label:'Data da aprovação'},{key:'avaliacao',label:'Avaliação'},{key:'motivo',label:'Motivo'}]} rows={orders.filter(order=>order.rating).map(order=>({ordem:order.id,solicitante:order.requester,chamado:order.openedAt,aprovacao:order.approvedAt||'-',avaliacao:order.rating,motivo:order.ratingReason||'-'}))}/></div><div className="metric-grid">{ratings.map(rating=><article key={rating}><small>AVALIAÇÃO</small><b>{orders.filter(order=>order.rating===rating).length}</b><span>{rating}</span></article>)}</div><section className="panel review-list"><h2>Histórico de avaliações</h2>{orders.filter(order=>order.rating).map(order=><article key={order.id}><Star/><div><b>{order.id} · {order.request}</b><small>{order.requester} · {order.technician||'Técnico não informado'} · {order.closedAt||'Data não informada'}</small><p>{order.ratingReason||'Motivo não informado.'}</p></div><strong>{order.rating}</strong></article>)}{!orders.some(order=>order.rating)&&<div className="empty-list">Nenhuma avaliação registrada.</div>}</section></section>}</>
}
