import React,{useEffect,useMemo,useState}from'react';
import{createPortal}from'react-dom';
import{AlertTriangle,CalendarDays,CarFront,DollarSign,Fuel,Gauge,Image,MapPin,Pencil,Plus,Save,ShieldCheck,Trash2,UserRound,Wrench,X}from'lucide-react';
import type{Company}from'./v2-types';
import{ExportButtons,type ExportColumn,type ExportRow}from'./data-export';

type Vehicle={id:number;company:Company;model:string;year:number;plate:string;color:string;chassis:string;photo:string;documents:string[];odometer:number;acquiredAt:string;driver:string};
type Maintenance={id:number;company:Company;vehicleId:number;kind:'Preventiva'|'Corretiva';date:string;description:string;cost:number;odometer:number;nextDate:string;nextOdometer:number};
type FuelEntry={id:number;company:Company;vehicleId:number;date:string;liters:number;cost:number;odometer:number};
type Obligation={id:number;company:Company;vehicleId:number;kind:'Seguro'|'IPVA'|'Licenciamento'|'Taxa';description:string;dueDate:string;cost:number;status:'Pendente'|'Pago'};
type Tab='dashboard'|'vehicles'|'maintenance'|'fuel'|'obligations';

const drivers:Record<Company,string[]>={Grafmarques:[],INFINNI:[],'M.Print':[]};
const vehicleSeed:Vehicle[]=[];
const maintenanceSeed:Maintenance[]=[];
const fuelSeed:FuelEntry[]=[];
const obligationSeed:Obligation[]=[];

function load<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value)as T:fallback}catch{return fallback}}
function notify(message:string){let banner=document.getElementById('v2-toast');if(!banner){banner=document.createElement('div');banner.id='v2-toast';banner.className='toast-inline';document.body.appendChild(banner)}banner.textContent=message;banner.style.display='flex';setTimeout(()=>banner!.style.display='none',2500)}
function money(value:number){return value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function date(value:string){return value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'-'}
function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:React.ReactNode;wide?:boolean}){return createPortal(<div className="overlay v2-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className={'modal v2-modal '+(wide?'vehicle-wide-modal':'')}><div><h2>{title}</h2><button type="button" aria-label="Fechar" onClick={close}><X/></button></div>{children}</div></div>,document.body)}
function Actions({edit,remove}:{edit:()=>void;remove:()=>void}){return <div className="vehicle-actions"><button type="button" title="Editar" onClick={edit}><Pencil/></button><button type="button" className="danger" title="Excluir" onClick={remove}><Trash2/></button></div>}
function VehicleForm({company,item,close,save}:{company:Company;item?:Vehicle;close:()=>void;save:(item:Vehicle)=>void}){const[photo,setPhoto]=useState(item?.photo||''),[documents,setDocuments]=useState<string[]>(item?.documents||[]),[error,setError]=useState('');return <Modal title={item?'Editar veiculo':'Cadastrar veiculo'} close={close} wide><form className="modal-form vehicle-form-grid" onSubmit={event=>{event.preventDefault();if(!photo){setError('A foto do veiculo e obrigatoria.');return}const data=new FormData(event.currentTarget);save({id:item?.id||Date.now(),company,model:String(data.get('model')),year:Number(data.get('year')),plate:String(data.get('plate')).toUpperCase(),color:String(data.get('color')),chassis:String(data.get('chassis')),photo,documents,odometer:Number(data.get('odometer')||0),acquiredAt:String(data.get('acquiredAt')),driver:String(data.get('driver'))});close()}}>{error&&<div className="form-alert full">{error}</div>}<label>Modelo do veiculo *<input name="model" defaultValue={item?.model} required/></label><label>Ano *<input name="year" type="number" min="1950" max="2100" defaultValue={item?.year} required/></label><label>Placa *<input name="plate" defaultValue={item?.plate} required placeholder="ABC-1D23"/></label><label>Cor<input name="color" defaultValue={item?.color}/></label><label>Numero de chassi<input name="chassis" defaultValue={item?.chassis}/></label><label>Hodometro (km)<input name="odometer" type="number" min="0" defaultValue={item?.odometer||0}/></label><label>Data de aquisicao<input name="acquiredAt" type="date" defaultValue={item?.acquiredAt}/></label><label>Motorista vinculado<select name="driver" defaultValue={item?.driver||''}><option value="">Sem motorista definido</option>{drivers[company].map(driver=><option key={driver}>{driver}</option>)}</select></label><label className="vehicle-photo-upload full">Foto do veiculo *<input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(file)}}/>{photo?<img src={photo}/>:<span><Image/>Selecionar foto obrigatoria</span>}</label><label className="vehicle-documents-upload full">Documentos do veículo (PDF ou foto)<input type="file" accept="application/pdf,image/*" multiple onChange={event=>{[...event.target.files||[]].forEach(file=>{const reader=new FileReader();reader.onload=()=>setDocuments(current=>[...current,String(reader.result)]);reader.readAsDataURL(file)})}}/><span>{documents.length?`${documents.length} documento(s) anexado(s)`:'Nenhum documento anexado'}</span></label><div className="form-actions full"><button type="button" onClick={close}>Cancelar</button><button className="primary"><Save/>Salvar veiculo</button></div></form></Modal>}

export default function VehicleMaintenance({company}:{company:Company}){
 const[tab,setTab]=useState<Tab>('dashboard'),[vehicles,setVehicles]=useState<Vehicle[]>(()=>load('operix.fleet.vehicles',vehicleSeed)),[maintenances,setMaintenances]=useState<Maintenance[]>(()=>load('operix.fleet.maintenances',maintenanceSeed)),[fuels,setFuels]=useState<FuelEntry[]>(()=>load('operix.fleet.fuels',fuelSeed)),[obligations,setObligations]=useState<Obligation[]>(()=>load('operix.fleet.obligations',obligationSeed)),[vehicleEditor,setVehicleEditor]=useState<Vehicle|null|undefined>(undefined),[maintenanceEditor,setMaintenanceEditor]=useState<Maintenance|null|undefined>(undefined),[fuelEditor,setFuelEditor]=useState<FuelEntry|null|undefined>(undefined),[obligationEditor,setObligationEditor]=useState<Obligation|null|undefined>(undefined);
 useEffect(()=>localStorage.setItem('operix.fleet.vehicles',JSON.stringify(vehicles)),[vehicles]);useEffect(()=>localStorage.setItem('operix.fleet.maintenances',JSON.stringify(maintenances)),[maintenances]);useEffect(()=>localStorage.setItem('operix.fleet.fuels',JSON.stringify(fuels)),[fuels]);useEffect(()=>localStorage.setItem('operix.fleet.obligations',JSON.stringify(obligations)),[obligations]);
 const fleet=useMemo(()=>vehicles.filter(item=>item.company===company),[vehicles,company]),vehicleIds=new Set(fleet.map(item=>item.id)),companyMaintenances=maintenances.filter(item=>vehicleIds.has(item.vehicleId)),companyFuels=fuels.filter(item=>vehicleIds.has(item.vehicleId)),companyObligations=obligations.filter(item=>vehicleIds.has(item.vehicleId)),vehicleName=(id:number)=>fleet.find(item=>item.id===id)?.model||'Veiculo removido',maintenanceCost=companyMaintenances.reduce((sum,item)=>sum+item.cost,0),fuelCost=companyFuels.reduce((sum,item)=>sum+item.cost,0),liters=companyFuels.reduce((sum,item)=>sum+item.liters,0),kmDriven=fleet.reduce((sum,vehicle)=>{const entries=companyFuels.filter(item=>item.vehicleId===vehicle.id).sort((a,b)=>a.odometer-b.odometer);return sum+(entries.length>1?entries.at(-1)!.odometer-entries[0].odometer:0)},0),efficiency=liters?kmDriven/liters:0,overdue=companyObligations.filter(item=>item.status==='Pendente'&&item.dueDate<new Date().toISOString().slice(0,10));
 const saveVehicle=(record:Vehicle)=>{setVehicles(current=>current.some(item=>item.id===record.id)?current.map(item=>item.id===record.id?record:item):[record,...current]);notify(vehicleEditor?'Veiculo atualizado.':'Veiculo cadastrado.')};
 const tabs:[Tab,string,React.ReactNode][]=[['dashboard','Painel',<Gauge/>],['vehicles','Veículos',<CarFront/>],['maintenance','Manutenções',<Wrench/>],['fuel','Abastecimentos',<Fuel/>],['obligations','Seguros e taxas',<ShieldCheck/>]];
 const exportData:{title:string;columns:ExportColumn[];rows:ExportRow[]}=tab==='vehicles'?{title:`Veículos - ${company}`,columns:[{key:'modelo',label:'Modelo'},{key:'ano',label:'Ano'},{key:'placa',label:'Placa'},{key:'motorista',label:'Motorista'},{key:'hodometro',label:'Hodômetro'}],rows:fleet.map(item=>({modelo:item.model,ano:item.year,placa:item.plate,motorista:item.driver||'Não vinculado',hodometro:item.odometer}))}:tab==='maintenance'?{title:`Manutenções da frota - ${company}`,columns:[{key:'veiculo',label:'Veículo'},{key:'tipo',label:'Tipo'},{key:'data',label:'Data'},{key:'servico',label:'Serviço'},{key:'custo',label:'Custo'}],rows:companyMaintenances.map(item=>({veiculo:vehicleName(item.vehicleId),tipo:item.kind,data:date(item.date),servico:item.description,custo:money(item.cost)}))}:tab==='fuel'?{title:`Abastecimentos - ${company}`,columns:[{key:'veiculo',label:'Veículo'},{key:'data',label:'Data'},{key:'litros',label:'Litros'},{key:'valor',label:'Valor'},{key:'hodometro',label:'Hodômetro'}],rows:companyFuels.map(item=>({veiculo:vehicleName(item.vehicleId),data:date(item.date),litros:item.liters,valor:money(item.cost),hodometro:item.odometer}))}:tab==='obligations'?{title:`Seguros e taxas - ${company}`,columns:[{key:'veiculo',label:'Veículo'},{key:'tipo',label:'Tipo'},{key:'descricao',label:'Descrição'},{key:'vencimento',label:'Vencimento'},{key:'valor',label:'Valor'},{key:'status',label:'Status'}],rows:companyObligations.map(item=>({veiculo:vehicleName(item.vehicleId),tipo:item.kind,descricao:item.description,vencimento:date(item.dueDate),valor:money(item.cost),status:item.status}))}:{title:`Resumo da frota - ${company}`,columns:[{key:'indicador',label:'Indicador'},{key:'valor',label:'Valor'}],rows:[{indicador:'Veículos',valor:fleet.length},{indicador:'Custo de manutenção',valor:money(maintenanceCost)},{indicador:'Combustível',valor:money(fuelCost)},{indicador:'Consumo médio',valor:`${efficiency.toFixed(1)} km/l`}]};
 return <section className="content page-enter"><div className="page-title"><div><span>FROTA - {company}</span><h1>Gestão de frota</h1><p>Veículos, motoristas, manutenções, consumo, seguros e taxas da empresa ativa.</p></div><div className="page-title-actions"><ExportButtons {...exportData}/>{tab==='vehicles'&&<button className="primary" onClick={()=>setVehicleEditor(null)}><Plus/>Cadastrar veículo</button>}{tab==='maintenance'&&<button className="primary" disabled={!fleet.length} onClick={()=>setMaintenanceEditor(null)}><Plus/>Nova manutenção</button>}{tab==='fuel'&&<button className="primary" disabled={!fleet.length} onClick={()=>setFuelEditor(null)}><Plus/>Novo abastecimento</button>}{tab==='obligations'&&<button className="primary" disabled={!fleet.length} onClick={()=>setObligationEditor(null)}><Plus/>Novo seguro ou taxa</button>}</div></div><div className="management-tabs fleet-tabs">{tabs.map(([id,label,icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{icon}{label}</button>)}</div>
 {tab==='dashboard'&&<div className="fleet-dashboard"><div className="inventory-metrics fleet-metrics"><article><CarFront/><small>Veículos</small><b>{fleet.length}</b><span>Frota da empresa</span></article><article><Wrench/><small>Custo de manutenção</small><b>{money(maintenanceCost)}</b><span>Preventiva e corretiva</span></article><article><Fuel/><small>Combustível</small><b>{money(fuelCost)}</b><span>{liters.toFixed(1)} litros registrados</span></article><article><Gauge/><small>Média de consumo</small><b>{efficiency.toFixed(1)} km/l</b><span>{kmDriven.toLocaleString('pt-BR')} km medidos</span></article></div><div className="fleet-dashboard-grid"><section className="panel"><div className="content-head"><div><h2>Resumo da frota</h2><p>Hodômetro e motorista atual</p></div></div>{fleet.map(vehicle=><article className="fleet-summary-row" key={vehicle.id}>{vehicle.photo?<img src={vehicle.photo}/>:<CarFront/>}<div><b>{vehicle.model}</b><small>{vehicle.plate} · {vehicle.year}</small></div><span><UserRound/>{vehicle.driver||'Sem motorista'}</span><strong>{vehicle.odometer.toLocaleString('pt-BR')} km</strong></article>)}{!fleet.length&&<div className="empty-list">Cadastre o primeiro veiculo da empresa.</div>}</section><section className="panel"><div className="content-head"><div><h2>Vencimentos e alertas</h2><p>Seguros, taxas e preventivas</p></div></div>{overdue.map(item=><article className="fleet-alert" key={item.id}><AlertTriangle/><div><b>{item.kind} vencido</b><small>{vehicleName(item.vehicleId)} · {date(item.dueDate)}</small></div></article>)}{companyObligations.filter(item=>item.status==='Pendente'&&!overdue.includes(item)).slice(0,5).map(item=><article className="fleet-alert upcoming" key={item.id}><CalendarDays/><div><b>{item.kind}: {item.description}</b><small>{vehicleName(item.vehicleId)} · {date(item.dueDate)}</small></div></article>)}{!companyObligations.length&&<div className="empty-list">Nenhum vencimento cadastrado.</div>}</section></div></div>}
 {tab==='vehicles'&&<div className="fleet-card-grid">{fleet.map(vehicle=><article className="panel vehicle-card" key={vehicle.id}><div className="vehicle-card-photo">{vehicle.photo?<img src={vehicle.photo}/>:<CarFront/>}</div><div className="vehicle-card-head"><div><span>{vehicle.plate}</span><h2>{vehicle.model}</h2><p>{vehicle.year}{vehicle.color?` · ${vehicle.color}`:''}</p></div><Actions edit={()=>setVehicleEditor(vehicle)} remove={()=>{setVehicles(current=>current.filter(item=>item.id!==vehicle.id));setMaintenances(current=>current.filter(item=>item.vehicleId!==vehicle.id));setFuels(current=>current.filter(item=>item.vehicleId!==vehicle.id));setObligations(current=>current.filter(item=>item.vehicleId!==vehicle.id));notify('Veiculo e registros vinculados excluidos.')}}/></div><dl><div><dt>Motorista</dt><dd>{vehicle.driver||'Nao vinculado'}</dd></div><div><dt>Hodometro</dt><dd>{vehicle.odometer.toLocaleString('pt-BR')} km</dd></div><div><dt>Chassi</dt><dd>{vehicle.chassis||'-'}</dd></div><div><dt>Aquisicao</dt><dd>{date(vehicle.acquiredAt)}</dd></div></dl></article>)}{!fleet.length&&<div className="empty-list">Nenhum veiculo cadastrado para {company}.</div>}</div>}
 {tab==='maintenance'&&<section className="panel fleet-table-panel"><div className="fleet-table"><div className="fleet-table-row head"><span>Veiculo</span><span>Tipo</span><span>Data / hodometro</span><span>Servico</span><span>Custo</span><span>Proxima</span><span>Acoes</span></div>{companyMaintenances.map(item=><div className="fleet-table-row" key={item.id}><b>{vehicleName(item.vehicleId)}</b><span className={item.kind==='Preventiva'?'preventive':'corrective'}>{item.kind}</span><span>{date(item.date)}<small>{item.odometer.toLocaleString('pt-BR')} km</small></span><span>{item.description}</span><strong>{money(item.cost)}</strong><span>{date(item.nextDate)}{item.nextOdometer>0&&<small>{item.nextOdometer.toLocaleString('pt-BR')} km</small>}</span><Actions edit={()=>setMaintenanceEditor(item)} remove={()=>{setMaintenances(current=>current.filter(record=>record.id!==item.id));notify('Manutencao excluida.')}}/></div>)}</div>{!companyMaintenances.length&&<div className="empty-list">Nenhuma manutencao registrada.</div>}</section>}
 {tab==='fuel'&&<section className="panel fleet-table-panel"><div className="fleet-table fuel-table"><div className="fleet-table-row head"><span>Veiculo</span><span>Data</span><span>Litros</span><span>Valor</span><span>Hodometro</span><span>Km/l</span><span>Acoes</span></div>{companyFuels.map(item=>{const previous=companyFuels.filter(entry=>entry.vehicleId===item.vehicleId&&entry.odometer<item.odometer).sort((a,b)=>b.odometer-a.odometer)[0],average=previous&&item.liters?(item.odometer-previous.odometer)/item.liters:0;return <div className="fleet-table-row" key={item.id}><b>{vehicleName(item.vehicleId)}</b><span>{date(item.date)}</span><span>{item.liters.toFixed(1)} L</span><strong>{money(item.cost)}</strong><span>{item.odometer.toLocaleString('pt-BR')} km</span><span>{average?`${average.toFixed(1)} km/l`:'-'}</span><Actions edit={()=>setFuelEditor(item)} remove={()=>{setFuels(current=>current.filter(record=>record.id!==item.id));notify('Abastecimento excluido.')}}/></div>})}</div>{!companyFuels.length&&<div className="empty-list">Nenhum abastecimento registrado.</div>}</section>}
 {tab==='obligations'&&<section className="panel fleet-table-panel"><div className="fleet-table obligation-table"><div className="fleet-table-row head"><span>Veiculo</span><span>Tipo</span><span>Descricao</span><span>Vencimento</span><span>Valor</span><span>Status</span><span>Acoes</span></div>{companyObligations.map(item=><div className="fleet-table-row" key={item.id}><b>{vehicleName(item.vehicleId)}</b><span>{item.kind}</span><span>{item.description}</span><span>{date(item.dueDate)}</span><strong>{money(item.cost)}</strong><span className={item.status==='Pago'?'paid':'pending'}>{item.status}</span><Actions edit={()=>setObligationEditor(item)} remove={()=>{setObligations(current=>current.filter(record=>record.id!==item.id));notify('Obrigacao excluida.')}}/></div>)}</div>{!companyObligations.length&&<div className="empty-list">Nenhum seguro ou taxa cadastrado.</div>}</section>}
 {vehicleEditor!==undefined&&<VehicleForm company={company} item={vehicleEditor||undefined} close={()=>setVehicleEditor(undefined)} save={saveVehicle}/>} 
 {maintenanceEditor!==undefined&&<Modal title={maintenanceEditor?'Editar manutencao':'Nova manutencao'} close={()=>setMaintenanceEditor(undefined)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),record:Maintenance={id:maintenanceEditor?.id||Date.now(),company,vehicleId:Number(data.get('vehicleId')),kind:String(data.get('kind'))as Maintenance['kind'],date:String(data.get('date')),description:String(data.get('description')),cost:Number(data.get('cost')),odometer:Number(data.get('odometer')),nextDate:String(data.get('nextDate')),nextOdometer:Number(data.get('nextOdometer')||0)};setMaintenances(current=>maintenanceEditor?current.map(item=>item.id===record.id?record:item):[record,...current]);setMaintenanceEditor(undefined);notify('Manutencao salva.')}}><label>Veiculo<select name="vehicleId" defaultValue={maintenanceEditor?.vehicleId||fleet[0]?.id}>{fleet.map(vehicle=><option value={vehicle.id} key={vehicle.id}>{vehicle.model} · {vehicle.plate}</option>)}</select></label><label>Tipo<select name="kind" defaultValue={maintenanceEditor?.kind||'Preventiva'}><option>Preventiva</option><option>Corretiva</option></select></label><label>Data<input name="date" type="date" defaultValue={maintenanceEditor?.date} required/></label><label>Descricao<textarea name="description" defaultValue={maintenanceEditor?.description} required/></label><label>Custo<input name="cost" type="number" min="0" step="0.01" defaultValue={maintenanceEditor?.cost}/></label><label>Hodometro<input name="odometer" type="number" min="0" defaultValue={maintenanceEditor?.odometer}/></label><label>Proxima data<input name="nextDate" type="date" defaultValue={maintenanceEditor?.nextDate}/></label><label>Proximo hodometro<input name="nextOdometer" type="number" min="0" defaultValue={maintenanceEditor?.nextOdometer}/></label><button className="primary"><Save/>Salvar manutencao</button></form></Modal>}
 {fuelEditor!==undefined&&<Modal title={fuelEditor?'Editar abastecimento':'Novo abastecimento'} close={()=>setFuelEditor(undefined)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),record:FuelEntry={id:fuelEditor?.id||Date.now(),company,vehicleId:Number(data.get('vehicleId')),date:String(data.get('date')),liters:Number(data.get('liters')),cost:Number(data.get('cost')),odometer:Number(data.get('odometer'))};setFuels(current=>fuelEditor?current.map(item=>item.id===record.id?record:item):[record,...current]);setVehicles(current=>current.map(vehicle=>vehicle.id===record.vehicleId&&record.odometer>vehicle.odometer?{...vehicle,odometer:record.odometer}:vehicle));setFuelEditor(undefined);notify('Abastecimento salvo e hodometro atualizado.')}}><label>Veiculo<select name="vehicleId" defaultValue={fuelEditor?.vehicleId||fleet[0]?.id}>{fleet.map(vehicle=><option value={vehicle.id} key={vehicle.id}>{vehicle.model} · {vehicle.plate}</option>)}</select></label><label>Data<input name="date" type="date" defaultValue={fuelEditor?.date} required/></label><label>Litros<input name="liters" type="number" min="0.01" step="0.01" defaultValue={fuelEditor?.liters} required/></label><label>Valor total<input name="cost" type="number" min="0" step="0.01" defaultValue={fuelEditor?.cost} required/></label><label>Hodometro<input name="odometer" type="number" min="0" defaultValue={fuelEditor?.odometer} required/></label><button className="primary"><Save/>Salvar abastecimento</button></form></Modal>}
 {obligationEditor!==undefined&&<Modal title={obligationEditor?'Editar seguro ou taxa':'Novo seguro ou taxa'} close={()=>setObligationEditor(undefined)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),record:Obligation={id:obligationEditor?.id||Date.now(),company,vehicleId:Number(data.get('vehicleId')),kind:String(data.get('kind'))as Obligation['kind'],description:String(data.get('description')),dueDate:String(data.get('dueDate')),cost:Number(data.get('cost')),status:String(data.get('status'))as Obligation['status']};setObligations(current=>obligationEditor?current.map(item=>item.id===record.id?record:item):[record,...current]);setObligationEditor(undefined);notify('Seguro ou taxa salvo.')}}><label>Veiculo<select name="vehicleId" defaultValue={obligationEditor?.vehicleId||fleet[0]?.id}>{fleet.map(vehicle=><option value={vehicle.id} key={vehicle.id}>{vehicle.model} · {vehicle.plate}</option>)}</select></label><label>Tipo<select name="kind" defaultValue={obligationEditor?.kind||'Seguro'}><option>Seguro</option><option>IPVA</option><option>Licenciamento</option><option>Taxa</option></select></label><label>Descricao<input name="description" defaultValue={obligationEditor?.description} required/></label><label>Vencimento<input name="dueDate" type="date" defaultValue={obligationEditor?.dueDate} required/></label><label>Valor<input name="cost" type="number" min="0" step="0.01" defaultValue={obligationEditor?.cost}/></label><label>Status<select name="status" defaultValue={obligationEditor?.status||'Pendente'}><option>Pendente</option><option>Pago</option></select></label><button className="primary"><Save/>Salvar seguro ou taxa</button></form></Modal>}
 </section>
}
