import React,{useEffect,useState}from'react';
import{createPortal}from'react-dom';
import{AlertTriangle,ArrowDown,ArrowUp,Boxes,Check,ClipboardCheck,Package,Plus,Search,ShoppingCart,Warehouse,X}from'lucide-react';
import SignaturePad from'./SignaturePad';
import type{Company,Role}from'./v2-types';
import{ExportButtons}from'./data-export';
import WarehouseFulfillmentModal,{type WarehouseFulfillment}from'./WarehouseFulfillmentModal';

type Inventory={id:number;company:Company;name:string;sector:string;responsible:string;location:string};
type Item={id:number;company:Company;inventoryId:number;name:string;category:string;unit:string;stock:number;minimum:number;asset:boolean;patrimony:string;value:number};
type Request={id:string;company:Company;inventoryId:number;requester:string;sector:string;item:string;quantity:number;reason:string;signature:string;status:'Aguardando'|'Em separação'|'Entregue'|'Negada';response?:string;attendant?:string;deliveryDate?:string;deliveredQuantity?:number;notes?:string;proof?:string;attendantSignature?:string;receiverSignature?:string};
const inventoriesSeed:Inventory[]=[];
const itemsSeed:Item[]=[];
const requestsSeed:Request[]=[];
const load=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'')as T}catch{return fallback}};
const notify=(message:string)=>{let box=document.getElementById('v2-toast');if(!box){box=document.createElement('div');box.id='v2-toast';box.className='toast-inline';document.body.appendChild(box)}box.textContent=message;box.style.display='flex';setTimeout(()=>box!.style.display='none',2500)};
function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:React.ReactNode;wide?:boolean}){return createPortal(<div className="overlay v2-overlay warehouse-modal-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className={`modal v2-modal ${wide?'warehouse-wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div><h2>{title}</h2><button type="button" aria-label="Fechar" onClick={close}><X/></button></div>{children}</div></div>,document.body)}

export function WarehouseRequestLauncher({company}:{company:Company}){
 const[open,setOpen]=useState(false),[confirmed,setConfirmed]=useState(false),[signature,setSignature]=useState(''),inventories=load<Inventory[]>('operix.warehouse.inventories',inventoriesSeed).filter(item=>item.company===company),items=load<Item[]>('operix.warehouse.items',itemsSeed).filter(item=>item.company===company);
 return <><button className="request-launch-card" onClick={()=>setOpen(true)}><Package/><span><b>Solicitar item ou equipamento</b><small>Escolha o inventário, item, quantidade e assine</small></span><Check/></button>{open&&<Modal title="Solicitação ao almoxarifado" close={()=>setOpen(false)} wide><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(!signature||!confirmed){notify('Desenhe e confirme a assinatura.');return}const request:Request={id:'ALM-'+Date.now().toString().slice(-6),company,inventoryId:Number(data.get('inventoryId')),requester:(()=>{try{return JSON.parse(sessionStorage.getItem('operix.auth.user')||'{}').name||'Usuário'}catch{return'Usuário'}})(),sector:'Não informado',item:String(data.get('item')),quantity:Number(data.get('quantity')),reason:String(data.get('reason')),signature,status:'Aguardando'},current=load<Request[]>('operix.warehouse.requests',requestsSeed);localStorage.setItem('operix.warehouse.requests',JSON.stringify([request,...current]));setOpen(false);notify('Solicitação enviada ao almoxarifado.')}}><label>Inventário de origem<select name="inventoryId" required>{inventories.map(item=><option value={item.id} key={item.id}>{item.name} · {item.sector}</option>)}</select></label><label>Item ou equipamento<select name="item" required>{items.map(item=><option value={item.name} key={item.id}>{item.name} · saldo {item.stock}</option>)}</select></label><label>Quantidade<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Motivo ou atividade<textarea name="reason" minLength={5} required/></label><label>Assinatura do solicitante<SignaturePad value={signature} confirmed={confirmed} onChange={setSignature} onConfirmedChange={setConfirmed} label="assinatura da solicitação ao almoxarifado"/></label><button className="primary" disabled={!confirmed}><Check/>Enviar solicitação</button></form></Modal>}</>
}

export default function WarehouseV1({company,role}:{company:Company;role:Role}){
 const[tab,setTab]=useState<'overview'|'inventories'|'items'|'requests'|'purchases'>('overview'),[inventories,setInventories]=useState<Inventory[]>(()=>load('operix.warehouse.inventories',inventoriesSeed)),[items,setItems]=useState<Item[]>(()=>load('operix.warehouse.items',itemsSeed)),[requests,setRequests]=useState<Request[]>(()=>load('operix.warehouse.requests',requestsSeed)),[inventoryOpen,setInventoryOpen]=useState(false),[itemOpen,setItemOpen]=useState(false),[selectedInventory,setSelectedInventory]=useState<Inventory|null>(null),[selectedRequest,setSelectedRequest]=useState<Request|null>(null),[search,setSearch]=useState('');
 useEffect(()=>localStorage.setItem('operix.warehouse.inventories',JSON.stringify(inventories)),[inventories]);useEffect(()=>localStorage.setItem('operix.warehouse.items',JSON.stringify(items)),[items]);useEffect(()=>localStorage.setItem('operix.warehouse.requests',JSON.stringify(requests)),[requests]);
 const inv=inventories.filter(item=>item.company===company),list=items.filter(item=>item.company===company&&item.name.toLowerCase().includes(search.toLowerCase())),req=requests.filter(item=>item.company===company),low=list.filter(item=>item.stock<=item.minimum),total=list.reduce((sum,item)=>sum+item.stock*item.value,0),canManage=role!=='Padrao';
 const saveFulfillment=(data:WarehouseFulfillment,finalize:boolean)=>{if(!selectedRequest)return;setRequests(current=>current.map(request=>request.id===selectedRequest.id?{...request,...data}:request));if(finalize&&data.status==='Entregue'&&selectedRequest.status!=='Entregue'){setItems(current=>current.map(item=>item.inventoryId===selectedRequest.inventoryId&&item.name===selectedRequest.item?{...item,stock:Math.max(0,item.stock-data.deliveredQuantity)}:item))}setSelectedRequest(null);notify(finalize?data.status==='Negada'?'Solicitação negada com justificativa e assinatura.':'Entrega finalizada, assinada e baixada do estoque.':'Atendimento salvo para continuar depois.')};
 return <section className="content page-enter"><div className="page-title"><div><span>SUPRIMENTOS E PATRIMÔNIO</span><h1>Gestão de almoxarifado</h1><p>Inventários, estoque, patrimônio, compras e entregas com assinatura.</p></div><ExportButtons title={`Almoxarifado - ${company}`} columns={[{key:'item',label:'Item'},{key:'inventario',label:'Inventário'},{key:'saldo',label:'Saldo'},{key:'minimo',label:'Mínimo'},{key:'patrimonio',label:'Patrimônio'}]} rows={list.map(item=>({item:item.name,inventario:inv.find(current=>current.id===item.inventoryId)?.name,saldo:item.stock,minimo:item.minimum,patrimonio:item.patrimony}))}/></div><div className="management-tabs">{([['overview','Visão geral'],['inventories','Inventários'],['items','Itens e patrimônio'],['requests','Solicitações'],['purchases','Compras']]as const).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
 {tab==='overview'&&<><div className="inventory-metrics"><article><Warehouse/><small>Inventários</small><b>{inv.length}</b><span>Setores controlados</span></article><article><Boxes/><small>Itens cadastrados</small><b>{list.length}</b><span>{list.reduce((sum,item)=>sum+item.stock,0)} unidades</span></article><article className={low.length?'warning':''}><AlertTriangle/><small>Estoque mínimo</small><b>{low.length}</b><span>Precisam de reposição</span></article><article><ShoppingCart/><small>Valor estimado</small><b>{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b><span>Saldo patrimonial</span></article></div><div className="warehouse-inventory-grid">{inv.map(item=><button onClick={()=>setSelectedInventory(item)} key={item.id}><Warehouse/><div><b>{item.name}</b><small>{item.sector} · {item.location}</small><span>{list.filter(current=>current.inventoryId===item.id).length} itens · Responsável: {item.responsible}</span></div></button>)}</div></>}
 {tab==='inventories'&&<><div className="content-head"><h2>Inventários cadastrados</h2>{canManage&&<button className="primary" onClick={()=>setInventoryOpen(true)}><Plus/>Criar inventário</button>}</div><div className="warehouse-inventory-grid">{inv.map(item=><button onClick={()=>setSelectedInventory(item)} key={item.id}><Warehouse/><div><b>{item.name}</b><small>{item.sector} · {item.location}</small><span>{item.responsible}</span></div></button>)}</div></>}
 {tab==='items'&&<><div className="content-head"><label className="inventory-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Pesquisar item, equipamento ou patrimônio"/></label>{canManage&&<button className="primary" onClick={()=>setItemOpen(true)}><Plus/>Cadastrar item</button>}</div><div className="inventory-table"><div className="inventory-row head"><span>Item</span><span>Inventário</span><span>Categoria</span><span>Saldo</span><span>Mínimo</span><span>Patrimônio</span><span>Ações</span></div>{list.map(item=><div className="inventory-row" key={item.id}><div><Package/><span><b>{item.name}</b><small>{item.unit} · {item.value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</small></span></div><span>{inv.find(current=>current.id===item.inventoryId)?.name}</span><span>{item.category}</span><strong>{item.stock}</strong><span>{item.minimum}</span><span>{item.patrimony||'-'}</span><div><button onClick={()=>setItems(current=>current.map(record=>record.id===item.id?{...record,stock:record.stock+1}:record))}><ArrowUp/></button><button onClick={()=>setItems(current=>current.map(record=>record.id===item.id?{...record,stock:Math.max(0,record.stock-1)}:record))}><ArrowDown/></button></div></div>)}</div></>}
 {tab==='requests'&&<section className="panel warehouse-requests"><h2>Atendimento de solicitações</h2>{req.map(request=><article key={request.id}><span className="epi-status">{request.status}</span><div><b>{request.id} · {request.item}</b><small>{request.requester} · {request.sector} · {request.quantity} unidade(s)</small><p>{request.reason}</p>{request.response&&<p><b>Resposta:</b> {request.response}</p>}{request.deliveryDate&&<small>Entrega: {new Date(request.deliveryDate).toLocaleString('pt-BR')} · {request.attendant}</small>}</div>{canManage&&<div><button className="primary" onClick={()=>setSelectedRequest(request)}><ClipboardCheck/>{request.status==='Entregue'||request.status==='Negada'?'Ver atendimento':'Atender solicitação'}</button></div>}</article>)}</section>}
 {tab==='purchases'&&<section className="panel purchase-board"><h2>Necessidades de compra</h2>{low.map(item=><article key={item.id}><AlertTriangle/><div><b>{item.name}</b><small>Saldo {item.stock} · mínimo {item.minimum} · sugestão {Math.max(item.minimum*2-item.stock,1)} {item.unit}</small></div><button><ShoppingCart/>Gerar pedido</button></article>)}</section>}
 {selectedInventory&&<Modal title={selectedInventory.name} close={()=>setSelectedInventory(null)} wide><div className="inventory-balloon"><header><Warehouse/><div><b>{selectedInventory.sector}</b><small>{selectedInventory.location} · {selectedInventory.responsible}</small></div></header>{list.filter(item=>item.inventoryId===selectedInventory.id).map(item=><article key={item.id}><Package/><span><b>{item.name}</b><small>{item.category}{item.patrimony?` · ${item.patrimony}`:''}</small></span><strong>{item.stock} {item.unit}</strong></article>)}</div></Modal>}
 {inventoryOpen&&<Modal title="Criar inventário" close={()=>setInventoryOpen(false)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);setInventories(current=>[{id:Date.now(),company,name:String(data.get('name')),sector:String(data.get('sector')),responsible:String(data.get('responsible')),location:String(data.get('location'))},...current]);setInventoryOpen(false)}}><label>Nome<input name="name" required/></label><label>Setor<input name="sector" required/></label><label>Responsável<input name="responsible" required/></label><label>Localização<input name="location" required/></label><button className="primary"><Plus/>Criar inventário</button></form></Modal>}
 {itemOpen&&<Modal title="Cadastrar item ou equipamento" close={()=>setItemOpen(false)}><form className="modal-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);setItems(current=>[{id:Date.now(),company,inventoryId:Number(data.get('inventoryId')),name:String(data.get('name')),category:String(data.get('category')),unit:String(data.get('unit')),stock:Number(data.get('stock')),minimum:Number(data.get('minimum')),asset:data.get('asset')==='on',patrimony:String(data.get('patrimony')),value:Number(data.get('value'))},...current]);setItemOpen(false)}}><label>Inventário<select name="inventoryId">{inv.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Nome<input name="name" required/></label><label>Categoria<input name="category" required/></label><label>Unidade<input name="unit" defaultValue="un" required/></label><label>Saldo inicial<input name="stock" type="number" min="0" required/></label><label>Estoque mínimo<input name="minimum" type="number" min="0" required/></label><label>Valor unitário<input name="value" type="number" step="0.01" min="0"/></label><label><input name="asset" type="checkbox"/> Bem patrimonial</label><label>Número de patrimônio<input name="patrimony"/></label><button className="primary"><Plus/>Cadastrar item</button></form></Modal>}
 {selectedRequest&&<WarehouseFulfillmentModal request={selectedRequest} close={()=>setSelectedRequest(null)} save={saveFulfillment}/>}</section>
}
